name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dart
        uses: dart-lang/setup-dart@v1

      - name: Install Melos
        run: dart pub global activate melos

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: npm ci

      - name: Check formatting
        run: npm run prettier:check

      - name: Check lint rules
        run: npm run lint

      - name: Start Xvfb
        if: runner.os == 'Linux'
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99.0" >>$GITHUB_ENV

      # This ensures that the local installation of Melos has been resolved before
      # running the tests.
      - name: Prepare test workspace
        working-directory: src/workspaces/suite
        run: melos

      - name: Run tests
        run: npm test
